import test from 'node:test';import assert from 'node:assert/strict';import {onRequest} from '../.cache/dist-test/functions/api/organizer-claim.js';
const payload={year:'2026',event_id:'R000175',organizer_name:'ŠD Test',contact_name:'Ana',organizer_email:'ana@example.com',declaration:true,displayed_snapshot_hash:'a'.repeat(64)};
const call=(body=payload,env={STK_ORGANIZER_CLAIM_RELAY_ENABLED:'true'},headers={})=>onRequest({request:new Request('https://stk.test/api/organizer-claim',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)}),env});
test('relay is POST only, JSON only and disabled by default',async()=>{let r=await onRequest({request:new Request('https://stk.test'),env:{}});assert.equal(r.status,405);r=await onRequest({request:new Request('https://stk.test',{method:'POST'}),env:{}});assert.equal(r.status,503);assert.equal((await r.json()).status,'NOT_CONFIGURED');r=await onRequest({request:new Request('https://stk.test',{method:'POST',body:'x'}),env:{STK_ORGANIZER_CLAIM_RELAY_ENABLED:'true'}});assert.equal(r.status,415)});
test('relay validates exact schema, email, hash and body limit',async()=>{assert.equal((await call({...payload,note:'x'})).status,400);assert.equal((await call({...payload,organizer_email:'bad'})).status,400);assert.equal((await call({...payload,displayed_snapshot_hash:'A'.repeat(64)})).status,400);assert.equal((await call(payload,undefined,{'content-length':'8193'})).status,413)});
test('relay sanitizes accepted and changed upstream responses',async(t)=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);globalThis.fetch=async()=>new Response(JSON.stringify({ok:true,status:'ACCEPTED',claim_id:'secret'}),{status:200,headers:{'x-secret':'x'}});let r=await call();assert.deepEqual(await r.json(),{ok:true,status:'ACCEPTED'});assert.equal(r.headers.get('x-secret'),null);assert.equal(r.headers.get('cache-control'),'no-store');globalThis.fetch=async()=>new Response(JSON.stringify({ok:false,code:'SNAPSHOT_CHANGED',reason:'private'}),{status:409});r=await call();assert.equal(r.status,409);assert.deepEqual(await r.json(),{ok:false,status:'SNAPSHOT_CHANGED'})});
test('relay converts non-JSON and network failure to safe unavailable',async(t)=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);globalThis.fetch=async()=>new Response('upstream detail');let r=await call();assert.deepEqual(await r.json(),{ok:false,status:'UNAVAILABLE'});globalThis.fetch=async()=>{throw new Error('private')};r=await call();assert.deepEqual(await r.json(),{ok:false,status:'UNAVAILABLE'})});

test('relay reads backend failure code and ignores failure status',async(t)=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);globalThis.fetch=async()=>new Response(JSON.stringify({ok:false,status:'SNAPSHOT_CHANGED'}),{status:409});const r=await call();assert.equal(r.status,503);assert.deepEqual(await r.json(),{ok:false,status:'UNAVAILABLE'})});
