import { allPlanningWeekends, buildPlanningOverview, buildPlanningWeeks, fetchPlanning2027, filterPlanningEvents, formatEventPlanningDate, formatPlanningEventCount, formatPlanningRange, formatPlanningRegion, formatPlanningSurface, formatPlanningUpdated, type PlanningEvent, type PlanningPayload } from './utils-planning-2027';
type Lang='sl'|'en';
const esc=(v:string|number)=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const months=(lang:Lang)=>lang==='en'?['January','February','March','April','May','June','July','August','September','October','November','December']:['Januar','Februar','Marec','April','Maj','Junij','Julij','Avgust','September','Oktober','November','December'];
const copy=(lang:Lang)=>lang==='en'?{confirmed:'confirmed',expected:'expected',known:'date window known',weekend:'Weekend',weekday:'Weekday',show:'Show events',unknown:'Date not yet known',location:'Location not provided',events:'events'}:{confirmed:'potrjeno',expected:'pričakovano',known:'termin znan',weekend:'Vikend',weekday:'Med tednom',show:'Prikaži dogodke',unknown:'Datum še ni znan',location:'Kraj ni naveden',events:'dogodkov'};
function eventHtml(e:PlanningEvent,lang:Lang){const l=copy(lang);const status=e.status==='potrjeno'?(lang==='en'?'Confirmed':'Potrjeno'):e.status==='termin_znan'?(lang==='en'?'Date window known':'Termin znan'):(lang==='en'?'Expected · STK estimate':'Pričakovano · ocena STK');const meta=[e.kraj||l.location,formatPlanningRegion(e.regija,lang),formatPlanningSurface(e.tip_podlage,lang)].filter(Boolean).map(esc).join(' · ');return `<li class="planning-event"><div class="planning-event-main"><strong>${esc(e.naziv_prireditve)}</strong><span>${meta}</span><time>${esc(formatEventPlanningDate(e,lang))}</time><em>${status}</em></div></li>`;}
export function renderPlanningOverview(root:HTMLElement,events:PlanningEvent[],lang:Lang,selectedMonth=''):void{
 const l=copy(lang), overview=buildPlanningOverview(events), weeks=buildPlanningWeeks(events), names=months(lang), weekendCounts=new Map(overview.weekends.map(w=>[w.start,w.total]));
 const year=root.querySelector<HTMLElement>('[data-year-overview]'); const planner=root.querySelector<HTMLElement>('[data-planning-weeks]'); const unknown=root.querySelector<HTMLElement>('[data-unknown-events]'); const empty=root.querySelector<HTMLElement>('[data-empty-results]'); if(!year||!planner||!unknown||!empty)return;
 year.innerHTML=names.map((name,i)=>{const month=String(i+1).padStart(2,'0');if(selectedMonth&&selectedMonth!==month)return'';const cells=allPlanningWeekends().filter(w=>w.month===month).map(w=>{const n=weekendCounts.get(w.start)??0,label=`${formatPlanningRange(w.start,w.end,lang,false)}: ${formatPlanningEventCount(n,lang)}`,content=`<span>${Number(w.start.slice(8))}.</span><strong>${n>=3?'3+':n}</strong>`;return n>0?`<a href="#week-${w.start}" class="weekend-count count-${Math.min(n,3)}" aria-label="${esc(label)}">${content}</a>`:`<span class="weekend-count count-0" role="img" aria-label="${esc(label)}">${content}</span>`}).join('');return `<section class="year-month" data-month="${month}"><a href="#month-${month}"><strong>${name}</strong></a><div>${cells}</div></section>`}).join('');
 planner.innerHTML=names.map((name,i)=>{const month=String(i+1).padStart(2,'0');const list=weeks.filter(w=>w.weekendStart.slice(5,7)===month);if(!list.length)return'';return `<section class="planning-month" id="month-${month}"><h2>${name}</h2><div>${list.map(w=>`<article class="planning-week" id="week-${w.weekendStart}"><h3>${esc(formatPlanningRange(w.start,w.end,lang))}</h3><p class="week-counts"><strong>${w.weekendEvents.length} ${lang==='en'?'weekend':'vikend'}</strong><span>${w.weekdayEvents.length} ${lang==='en'?'weekday':'med tednom'}</span></p><p class="week-statuses">${w.confirmed} ${l.confirmed} · ${w.expected} ${l.expected} · ${w.known} ${l.known}</p><details><summary>${l.show} ${formatPlanningEventCount(w.events.length,lang,'show')}</summary><ul class="planning-events">${w.events.map(e=>eventHtml(e,lang)).join('')}</ul></details></article>`).join('')}</div></section>`}).join('');
 unknown.hidden=overview.unknown.length===0;unknown.innerHTML=`<summary>${l.unknown} · ${formatPlanningEventCount(overview.unknown.length,lang)}</summary><ul class="planning-events">${overview.unknown.map(e=>eventHtml(e,lang)).join('')}</ul>`;empty.hidden=weeks.length>0;
}
export function initializePlanning2027(root:HTMLElement,initial:PlanningPayload|null,lang:Lang):void{let events=initial?.data??[];const content=root.querySelector<HTMLElement>('[data-planning-content]'),fallback=root.querySelector<HTMLElement>('[data-planning-fallback]'),selects=[...root.querySelectorAll<HTMLSelectElement>('[data-planning-filter]')],clear=root.querySelector<HTMLButtonElement>('[data-planning-clear]');
 const populate=()=>{for(const name of ['region','surface']){const select=selects.find(s=>s.name===name);if(!select)continue;const field=name==='region'?'regija':'tip_podlage',selected=select.value;while(select.options.length>1)select.remove(1);[...new Set(events.map(e=>e[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,lang)).forEach(v=>select.add(new Option(name==='region'?formatPlanningRegion(v,lang):formatPlanningSurface(v,lang),v)));select.value=[...select.options].some(o=>o.value===selected)?selected:'';}}
 const render=()=>{const v=Object.fromEntries(selects.map(s=>[s.name,s.value]));renderPlanningOverview(root,filterPlanningEvents(events,{month:v.month??'',region:v.region??'',surface:v.surface??''}),lang,v.month??'');const taxonomyFiltered=Boolean(v.region||v.surface);const note=root.querySelector<HTMLElement>('[data-planning-zero-note]');if(note)note.textContent=taxonomyFiltered?(lang==='en'?'Counts show events matching the selected filters. 0 means no currently known event matches the filters; it does not mean the date is available.':'Števila prikazujejo dogodke, ki ustrezajo izbranim filtrom. 0 pomeni, da noben trenutno znani dogodek ne ustreza filtrom; ne pomeni, da je termin prost.'):(lang==='en'?'0 events means STK currently has no known event for that weekend. It does not mean the date is available.':'0 dogodkov pomeni, da STK za ta vikend trenutno nima znanega dogodka. To ne pomeni, da je termin prost.');if(clear)clear.hidden=!selects.some(s=>s.value);};
 const show=(payload:PlanningPayload)=>{events=payload.data;populate();content!.hidden=false;if(fallback)fallback.hidden=true;const updated=root.querySelector<HTMLElement>('[data-planning-updated]');if(updated){const date=formatPlanningUpdated(payload.generated_at,lang);updated.hidden=!date;const time=updated.querySelector('time');if(time)time.textContent=date;}render();};
 selects.forEach(s=>s.addEventListener('change',render));clear?.addEventListener('click',()=>{selects.forEach(s=>s.value='');render();});if(initial)show(initial);fetchPlanning2027().then(p=>{if(p)show(p)});
}
